metrics:
  - default: cosine.yaml

collectors:
  - ensemble: MultiProxyCollector.yaml
  - repre: ProxyCollector.yaml

selectors:
  - loss1: DefaultSelector.yaml
  - loss2: DefaultSelector.yaml
  - loss3: DefaultSelector.yaml
  - loss4: DefaultSelector.yaml
  - loss: DefaultSelector.yaml

losses:
  - loss1: CosFaceLoss.yaml
  - loss2: CosFaceLoss.yaml
  - loss3: CosFaceLoss.yaml
  - loss4: CosFaceLoss.yaml
  - loss: CosFaceLoss.yaml

models:
  - trunk: bninception.yaml
  - embedder: relation_embedder.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: AdamW_trunk.yaml
  - embedder: AdamW_embedder.yaml
  - ensemble: AdamW_collector.yaml
  - repre: AdamW_collector.yaml

schedulers:
  - trunk: step_lr.yaml
  - embedder: step_lr.yaml
  - ensemble: step_lr.yaml
  - repre: step_lr.yaml

gradclipper:
  - trunk: gradclipper_model.yaml
  - embedder: gradclipper_model.yaml
  - ensemble: gradclipper_collector.yaml
  - repre: gradclipper_collector.yaml

transforms:
  - train: train_transforms.yaml
  - test: eval_transforms.yaml

datasets:
  - train: cub200_train.yaml
  - test: cub200_test.yaml

# samplers:
#   - train: MPerClassSampler.yaml

collatefns:
  - train: default.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING:
  to_device_list: [models, collectors]
