Cars196:
  params:
    root: /home/zbr/datasets/cars196
    phase: train
    assert_num_classes: 98
    assert_num_samples: 8054
    transform:
      - ~~_SEARCH_WITH_SAME_NAME_
      - transforms
      - none