ImageNet:
  params:
    root: /home/zbr/datasets/imagenet
    phase: test
    assert_num_classes: 1000
    assert_num_samples: 50000
    transform:
      - ~~_SEARCH_WITH_SAME_NAME_
      - transforms
      - none