eval_transforms:
  model_properties: [~~_SEARCH_WITH_TARGET_NAME_, models, trunk]
  compose_list:
    - Resize:
        size: 256
    - CenterCrop:
        size: 224
  wrapper: DefaultTransformWrapper