metrics:
  - default: euclid_normalized.yaml

collectors:
  - ensemble: MultiCollector.yaml
  - repre: DefaultCollector.yaml

selectors:
  - loss1: HardSelector.yaml
  - loss2: HardSelector.yaml
  - loss3: HardSelector.yaml
  - loss4: HardSelector.yaml
  - loss: HardSelector.yaml

losses:
  - loss1: TripletLoss.yaml
  - loss2: TripletLoss.yaml
  - loss3: TripletLoss.yaml
  - loss4: TripletLoss.yaml
  - loss: TripletLoss.yaml

models:
  - trunk: bninception.yaml
  - embedder: relation_embedder.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: AdamW_trunk.yaml
  - embedder: AdamW_embedder.yaml

schedulers:
  - trunk: step_lr.yaml
  - embedder: step_lr.yaml

gradclipper:
  - trunk: gradclipper_model.yaml
  - embedder: gradclipper_model.yaml

transforms:
  - train: train_transforms.yaml
  - test: eval_transforms.yaml

datasets:
  - train: cub200_train.yaml
  - test: cub200_test.yaml

samplers:
  - train: MPerClassFullSampler.yaml

collatefns:
  - train: default.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING:
  to_device_list: [models, collectors, losses]
