metrics:
  - default: euclid.yaml

collectors:
  - collector: DefaultCollector.yaml

selectors:
  - selector: HardSelector.yaml

losses:
  - loss: MarginLoss.yaml

models:
  - trunk: bninception.yaml
  - embedder: bninception_mlp.yaml

evaluators:
  - default: Calculator.yaml

optimizers:
  - trunk: AdamW_models.yaml
  - embedder: AdamW_models.yaml
  - loss: AdamW_losses.yaml

schedulers:
  - trunk: step_lr.yaml
  - embedder: step_lr.yaml
  - loss: step_lr.yaml

gradclipper:
  - trunk: gradclipper_models.yaml
  - embedder: gradclipper_models.yaml
  - loss: gradclipper_losses.yaml

transforms:
  - train: train_transforms.yaml
  - test: eval_transforms.yaml

datasets:
  - train: cub200_train.yaml
  - test: cub200_test.yaml

samplers:
  - train: MPerClassFullSampler.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING: 
  to_device_list: [models, losses]

PIPELINE_SETTING:
  models:
    trunk:
      input: [data]
      output: [data]
      map: 
        models/embedder: [0]
    embedder:
      input: [data]
      output: [embeddings]
      map:
        collectors/collector: [0]
  collectors:
    collector:
      input: [embeddings, labels]
      output: [metric_mat, row_labels, col_labels, is_same_source]
      map:
        selectors/selector: [0,1,2,3]
  selectors:
    selector:
      input: [metric_mat, row_labels, col_labels, is_same_source]
      output: [metric_mat, row_labels, col_labels, is_same_source, indices_tuple, weight]
      map:
        losses/loss: [0,1,2,3,4,5]
  losses:
    loss:
      input: [metric_mat, row_labels, col_labels, indices_tuple, weights, is_same_source]
      output: [loss]
      map:
        FINISH/default->margin_loss: [0]

